#Hrnet-Ocrnet configuration for Hrnet-W32 backbone network
HRNET_MODEL:
  ALIGN_CORNERS: true
  PRETRAINED: "imagenet_models/hrnetv2_w32_imagenet_pretrained.pth"           #path to pretrained imagenet weights
  CONFIGURATION:
    STEM_STRIDE: 4
    STEM_INPUT_CHANNEL: 3
    STEM_OUTPUT_CHANNEL: 64 
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 32
      - 64
      - 128
      - 256
      FUSE_METHOD: SUM
OCRNET_MODEL:
    RAW_IN_CHANNELS: 480
    PIXEL_REP_CHANNELS: 512
    KEY_CHANNELS: 256
    NUM_CLASSES: 17
    
    
